apiVersion: v1
kind: Service
metadata:
  name: client
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  ports:
   - port: 80
     name: http
     protocol: TCP
     targetPort: 80
  type: LoadBalancer
  selector:
    app: client